<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>False</Deterministic>
		<RepositoryUrl>https://github.com/RobertLeisner/Bodoconsult.Web</RepositoryUrl>
		<PackageId>Bodoconsult.Web.Ftp</PackageId>
		<PackageTags>FTP transfer files</PackageTags>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Simple .NET SFTP transfer modul based on SSH</Description>
		<PackageReleaseNotes>Migration to .NET 8, updated dependencies and add README.md</PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>

		<!-- PDB Configuration -->
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<EmbedAllSources>false</EmbedAllSources>

		<!-- Allow PDBs in the main package -->
		<!--
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>-->

		<!-- Generate symbols package (.snupkg) -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<!-- Modern symbols package format -->
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="nuget.txt" />
	  <None Remove="OpenSourceMetaData.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Graph" Version="6.6.0" />
		<PackageReference Include="SSH.NET" Version="2026.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\LICENSE.md" Link="LICENSE.md" />
		<Content Include="..\..\doc\Bodoconsult.Web.Ftp\README.md" Link="README.md" Pack="true" PackagePath="\">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
